Refactors status code handling in Airbyte client
PrefectHQ/prefect-airbyte pull request #20
Opened 2022-09-07 19:29 UTC by desertaxle

## Summary

Refactors the status code handling in the Airbyte client to handle all non 2xx status codes. Previously, status codes that did not match the preconfigured checks would fall through and cause unexpected errors. Now, we will raise on all non 2xx status codes and handle the exceptions in specific cases.

## Relevant Issue(s)

Closes #17 

## Checklist
- [x] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-airbyte/blob/main/CHANGELOG.md)

2022-09-07 20:43 UTC, ahuang11 commented on prefect_airbyte/client.py
> +            job_updated_at = response.json()["job"]["updatedAt"]
```suggestion
            job = response.json()["job"]
            job_status = job["status"]
            job_created_at = job["createdAt"]
            job_updated_at = job["updatedAt"]
```

2022-09-07 22:37 UTC, ahuang11 requested changes

2022-09-07 22:37 UTC, ahuang11 commented on prefect_airbyte/client.py
> +            return job_status, job_created_at, job_updated_at
I think the `Returns` section should be more explicit on what it return; and I don't think it's a byte array?

2022-09-07 22:37 UTC, ahuang11 commented on prefect_airbyte/client.py
> +            return job_id, job_created_at
```suggestion
            response.raise_for_status()
      
            job = response.json()["job"]
            job_id = job["id"]
            job_created_at = job["createdAt"]
            return job_id, job_created_at
```

I think the `Returns:` docstring section needs reformatting

2022-09-08 14:35 UTC, desertaxle commented on prefect_airbyte/client.py
> +            return job_status, job_created_at, job_updated_at
Addressed in [fcab2c8](https://github.com/PrefectHQ/prefect-airbyte/pull/20/commits/fcab2c88241fa672d36e4bb9e996c3436258b62c)

2022-09-08 15:25 UTC, ahuang11 approved these changes

2022-09-08 15:44 UTC, merged