add `stream_logs` parameter to `trigger_sync`
PrefectHQ/prefect-airbyte pull request #28
Opened 2022-09-17 23:27 UTC by zzstoatzz

## Summary
This PR includes exposes a `stream_logs` parameter to the `trigger_sync` task to surface airbyte sync logs through the Prefect logger and adds associated tests / fixtures.

This required refactoring `AirbyteClient.get_job_status` to conditionally return logs if `stream_output` is True.

This PR also switches from the standard python logger to the logger fetched by `get_run_logger()`, which required a change to all associate unit tests that were previously calling the `Task.fn()` method.

## Relevant Issue(s)
addresses #19 

## Checklist
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-airbyte/blob/main/CHANGELOG.md)

2022-09-19 22:34 UTC, ahuang11 requested changes
Looks nice! Can you share a screenshot/code snippet of what the output looks like?

2022-09-19 22:34 UTC, ahuang11 commented on prefect_airbyte/client.py
> +            attempts = response.json()["attempts"]
```suggestion
            contents = response.json()
            raw_job = contents["job"]
            attempts = contents["attempts"]
```

2022-09-19 22:34 UTC, ahuang11 commented on prefect_airbyte/connections.py
> +        stream_logs: whether to include airbyte job logs in Prefect task logs
```suggestion
        stream_logs: Whether to include airbyte job logs in Prefect task logs.
```

2022-09-19 22:34 UTC, ahuang11 commented on prefect_airbyte/client.py
> +            stream_logs: whether to capture Airbyte job logs in metadata.
Is there a downside if default `stream_logs=True`?

```suggestion
            stream_logs: Whether to capture Airbyte job logs in metadata.
```

2022-09-19 22:34 UTC, ahuang11 commented on prefect_airbyte/client.py
> +                job_info["logs"] = attempts[0]["logs"]["logLines"]
Is 0th index always the most recent or `-1`?

2022-09-19 22:34 UTC, ahuang11 commented on prefect_airbyte/client.py
> +            job_metadata
Can we elaborate what's in this new return value?

2022-09-19 22:34 UTC, ahuang11 commented on CHANGELOG.md
> +- logger used by all tasks from standard python logger to Prefect logger via `get_run_logger()`. As a consequence, also changed are the unit tests format, namely we're calling all tasks via a `test_f
```suggestion
- Logger used by all tasks from standard python logger to Prefect logger via `get_run_logger()`. As a consequence, also changed are the unit tests format, namely we're calling all tasks via a `test_flow` instead of calling tasks underlying function with `.fn()` to allow for use of the prefect logger - [#28](https://github.com/PrefectHQ/prefect-airbyte/pull/28)
```

By the way, it's possible to call `.fn` even with `get_run_logger` using `with prefect.logging.disable_run_logger: ...`

2022-09-19 22:34 UTC, ahuang11 commented on CHANGELOG.md
> +- return value of `AirbyteClient.get_job_status` to `job_metadata: dict` to simplify inclusion of logs and future job metadata fields - [#28](https://github.com/PrefectHQ/prefect-airbyte/pull/28)
```suggestion
- Return value of `AirbyteClient.get_job_status` to `job_metadata: dict` to simplify inclusion of logs and future job metadata fields - [#28](https://github.com/PrefectHQ/prefect-airbyte/pull/28)
```

2022-09-19 22:34 UTC, ahuang11 commented on CHANGELOG.md
> +- `stream_logs` parameter to `trigger_sync` to surface airbyte job logs through prefect logger - [#28](https://github.com/PrefectHQ/prefect-airbyte/pull/28)
```suggestion
- `stream_logs` parameter to `trigger_sync` to surface airbyte job logs through Prefect run logger - [#28](https://github.com/PrefectHQ/prefect-airbyte/pull/28)
```

2022-09-19 22:36 UTC, zzstoatzz commented on prefect_airbyte/client.py
> +                job_info["logs"] = attempts[0]["logs"]["logLines"]
They should be in descending order by `createdAt` according to the airbyte api docs

2022-09-19 22:37 UTC, zzstoatzz commented on CHANGELOG.md
> +- logger used by all tasks from standard python logger to Prefect logger via `get_run_logger()`. As a consequence, also changed are the unit tests format, namely we're calling all tasks via a `test_f
ahhh that'd have been useful - thanks!

2022-09-19 22:40 UTC, zzstoatzz commented on prefect_airbyte/client.py
> +            stream_logs: whether to capture Airbyte job logs in metadata.
Airbyte logs are super verbose so as a user I wouldn't want to see them by default, but totally open to changing this if we think its appropriate

2022-09-20 15:19 UTC, zzstoatzz commented on prefect_airbyte/client.py
> +                job_info["logs"] = attempts[0]["logs"]["logLines"]
hmm unfortunately they don't seem to be ordered as described in the docs, switching to `-1` index

2022-09-20 15:29 UTC, zzstoatzz commented
Sample output when `stream_logs=True` (logged at INFO level among `trigger_sync` task logs
```
2022-09-17 22:20:40 [32mINFO[m i.a.w.w.WorkerRun(call):49 - Executing worker wrapper. Airbyte version: 0.38.3-alpha
2022-09-17 22:20:40 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):108 - Docker volume job log path: /tmp/workspace/20534/0/logs.log
2022-09-17 22:20:40 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):113 - Executing worker wrapper. Airbyte version: 0.38.3-alpha

...

{"type":"string"},"Individual Filling out This Form":{"type":"string"},"Total of Each Fuel Transfer by Equipment":{"type":"string"}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}]],additionalProperties={}],failures=[]]
2022-09-17 22:20:50 [32mINFO[m i.a.w.t.TemporalUtils(withBackgroundHeartbeat):236 - Stopping temporal heartbeating...
```

2022-09-26 15:09 UTC, ahuang11 commented
Thanks for addressing the comments! Was wondering if this is ready for review?

2022-10-03 15:52 UTC, desertaxle requested changes
I like the direction that these changes takes us, but unfortunately there are some breaking changes. In order to support this I think we'll need to deprecate the current tasks and create a new ones to give users a smooth transition. The old tasks can emit a `DeprecationWarning` and guide users to use the new tasks/flows. This will also be a good chance to introduce a block, since that might lead to some breaking changes as well.

Let me know if there's any part of this that you'd like to discuss and/or pair on!

2022-11-14 22:32 UTC, closed without merging