Add `AirbyteServer` block **[breaking-changes]**
PrefectHQ/prefect-airbyte pull request #40
Opened 2022-11-14 22:37 UTC by zzstoatzz

Adds the `AirbyteServer` block to handle nginx authentication for OSS instance in `AirbyteClient` and store config info about the instance running airbyte.

This PR alters the tasks in this collection to accept an `AirbyteServer` instead of the individual fields, so these are breaking changes.

This PR also adds a deprecation warning to `export_configuration`, as the underlying API endpoint was removed from OSS airbyte as of airbyte v0.40.7

Closes #39 
Closes #21 

### Example

### Checklist

- [ ] This pull request includes tests or only affects documentation.
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-airbyte/blob/main/CHANGELOG.md)

2022-11-14 23:15 UTC, ahuang11 commented
Before I forget, I think we should add a changelog with the usual items and also highlight breaking changes in the first line.

2022-11-14 23:26 UTC, ahuang11 reviewed
Looks good! Mostly questions

2022-11-14 23:26 UTC, ahuang11 commented on prefect_airbyte/client.py
> +        yield client
Just a note that this is also a breaking change since it now only can be used as a contextmanager. We could theoretically make it not a breaking change by doing something similar to (with __aenter__ and __aexit__):
https://github.com/PrefectHQ/prefect-docker/blob/main/prefect_docker/host.py#L10-L25

2022-11-14 23:26 UTC, ahuang11 commented on prefect_airbyte/configuration.py
>  ) -> bytes:
Do we want to keep those other kwargs and slowly deprecate?

2022-11-14 23:26 UTC, ahuang11 commented on prefect_airbyte/server.py
> +
```suggestion
```

2022-11-14 23:26 UTC, ahuang11 commented on prefect_airbyte/server.py
> +    def get_client(self, logger: Logger, timeout: int = 10) -> AirbyteClient:
Should timeout be defined on the class?

2022-11-14 23:26 UTC, ahuang11 commented on prefect_airbyte/server.py
> +"""A module for defining OSS Airbyte interactions with Prefect."""
We need to update mkdocs.yml + server.md

2022-11-14 23:26 UTC, ahuang11 commented on prefect_airbyte/client.py
> +            # TODO - no current authentication methods from Airbyte
Is this comment still valid?

2022-11-14 23:26 UTC, ahuang11 commented on prefect_airbyte/server.py
> +class AirbyteServer(Block):
Should we name this `AirbyteServerCredentials` or `AirbyteCredentials`? (unsure if it's necessary, but consistent with most collections)

2022-11-14 23:26 UTC, ahuang11 commented on prefect_airbyte/server.py
> +    )
```suggestion
    title="API Version",
    )
```

2022-11-14 23:26 UTC, ahuang11 commented on prefect_airbyte/server.py
> +    )
```suggestion
    title="Use SSL",
    )
```

2022-11-14 23:26 UTC, ahuang11 commented on prefect_airbyte/server.py
> +    def airbyte_base_url(self) -> str:
we should mention in our style guide when we use `@property` vs fields

2022-11-15 01:41 UTC, zzstoatzz commented on prefect_airbyte/server.py
> +class AirbyteServer(Block):
I don't think so, because the concept of airbyte credentials will be shared with airbyte's cloud interface

this is what we briefly discussed earlier today where we thought this approach would make more sense than trying to anticipate their cloud interface or using `AirbyteCredentials` for OSS and then having to make future breaking changes

2022-11-15 01:43 UTC, zzstoatzz commented on prefect_airbyte/configuration.py
>  ) -> bytes:
good question, not sure

what do you think @desertaxle ?

2022-11-15 19:21 UTC, desertaxle requested changes

2022-11-15 19:21 UTC, desertaxle commented on prefect_airbyte/configuration.py
>  ) -> bytes:
That could be a way to avoid making an abrupt breaking change. If we accept these kwargs and then create an `AirbyteServer` block internally we could preserve the new code paths. We'd probably raise an error if a `AirbtyeServer` block is not passed in and direct users to update to use an `AirbyteServer` block instead of the kwargs.

That sounds like it's worth doing to me.

2022-11-15 19:21 UTC, desertaxle commented on prefect_airbyte/server.py
> +class AirbyteServer(Block):
Due to how rudimentary Airbyte's open source auth is, this is mostly server configuration. I'm good with `AirbyteServer`. Once Aribyte Cloud is available, I think we can name that block `AirbyteCloudCredentials`.

2022-11-15 21:41 UTC, zzstoatzz commented on prefect_airbyte/client.py
> +        yield client
I'm a little confused on how these would be implemented, unless we were going try and store the client object on the class itself

2022-11-16 00:45 UTC, ahuang11 requested changes
Thanks for making the changes!

2022-11-16 00:45 UTC, ahuang11 commented on CHANGELOG.md
> +This release introduces breaking changes by changing the default interface for tasks in this collection.
Can we add a little more specificity on this?

2022-11-16 00:45 UTC, ahuang11 commented on README.md
> +```
Maybe these can be separate examples as to not confuse the user (unless I'm confused)

2022-11-16 00:45 UTC, ahuang11 commented on prefect_airbyte/client.py
> +        )
Should this be private?

2022-11-16 00:45 UTC, ahuang11 commented on prefect_airbyte/client.py
> +        await self.check_health_status(self.client)
Should this be called in __init__ so that users that do not use the context managed version still get this?

2022-11-16 00:45 UTC, ahuang11 commented on prefect_airbyte/configuration.py
> -    airbyte_api_version: str = "v1",
Should we still have a dummy keyword arg so it doesn't crash on the user?

2022-11-16 00:45 UTC, ahuang11 commented on prefect_airbyte/connections.py
> -    airbyte_api_version: str = "v1",
Do we need a version

2022-11-16 00:45 UTC, ahuang11 commented on prefect_airbyte/connections.py
> +            )
Should we create a util for this?

2022-11-16 00:45 UTC, ahuang11 commented on prefect_airbyte/connections.py
> +                f"Connection {connection_id} is deprecated."
While we're making breaking changes, I wonder if this should be a flow, e.g. this functionality copied to a flow, extract the pieces into tasks (with unique names), and slowly deprecate this function?

2022-11-16 00:45 UTC, ahuang11 commented on prefect_airbyte/server.py
> +        title="Server Port",
If I'm not mistaken, I don't think we need `title` defined for these; only the ones with acronyms like API or SSL

2022-11-16 00:45 UTC, ahuang11 commented on prefect_airbyte/client.py
> -
Because this is a public method, to prevent breaking users' code, I think we still want to keep this function and add a deprecation warning.

2022-11-16 00:45 UTC, ahuang11 commented on prefect_airbyte/server.py
> +
`use_ssl` is missing here

2022-11-16 15:17 UTC, zzstoatzz commented on prefect_airbyte/client.py
> +        await self.check_health_status(self.client)
as is, it can't be called in `__init__` bc its async, and since we don't document / suggest any way of using this collection where users are manually creating clients, I'm not sure it feels necessary to account for that

2022-11-16 15:39 UTC, desertaxle requested changes
We're close enough to not making any breaking changes that I propose we don't make any. We can deprecate, continue with 0.1.x version releases, and then remove them in 0.2.0 when we've gotten this collection to our short term target state.

2022-11-16 15:39 UTC, desertaxle commented on prefect_airbyte/client.py
> +        )
I agree that this should probably be private.
```suggestion
        self._client = httpx.AsyncClient(
            base_url=self.airbyte_base_url, auth=self.auth, timeout=self.timeout
        )
```

2022-11-16 15:39 UTC, desertaxle commented on prefect_airbyte/client.py
> +        await self.check_health_status(self.client)
We can't call this in the `__init__` because it is an async method. I think this makes a lot of sense here.

2022-11-16 15:39 UTC, desertaxle commented on prefect_airbyte/connections.py
> -    airbyte_api_version: str = "v1",
Yeah, looks like we should keep an `airbyte_api_version` kwarg until we remove all the kwargs together in a later release.

2022-11-16 15:39 UTC, desertaxle commented on prefect_airbyte/connections.py
> +                f"Connection {connection_id} is deprecated."
I don't think we should make that change as part of this PR. We can use #22 for tracking that change. It'll be large enough that it should at least be its own PR, if not multiple PRs.

2022-11-16 15:39 UTC, desertaxle commented on prefect_airbyte/connections.py
> +            )
I recommend using a `DeprecationWarning` here instead of a warning level log message. `DeprecationWarninig` is a more accepted Python standard.

2022-11-16 15:39 UTC, desertaxle commented on prefect_airbyte/connections.py
> +            )
This is a tricky case. I agree that it's a good idea to tell the user that `airbyte_server` takes precedence, but I'm not sure that a warning log is the best way to do it. You've documented that `airbyte_server`, which is great. I think we could communicate a similar idea by logging the URL that we're using to call Airbyte.

2022-11-16 15:39 UTC, desertaxle commented on prefect_airbyte/client.py
> -
We're close enough to not making any breaking changes in this PR that I'm inclined to agree that we deprecate this method instead of removing it.

2022-11-16 19:49 UTC, desertaxle requested changes

2022-11-16 19:58 UTC, desertaxle approved these changes
🚢 it!

2022-11-16 20:21 UTC, merged